"""added city to user table and useraddform

Revision ID: 81ce2a74ecbf
Revises: 905aa6328f59
Create Date: 2024-02-29 10:22:45.688177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ce2a74ecbf'
down_revision = '905aa6328f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
